apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-deploy
  labels:
    app: backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: hollyrowena/ticketmanager
        ports: 
        - containerPort: 8080
        env:
        - name: dbport
          value: "3306"
        - name: dbpath
          value: %RDS_ENDPOINT%
        envFrom:
        - secretRef:
            name: aws-secrets